version: '3'
services:
  nodengnpm:
    image: nodengnpm2:v10
    container_name: nodengnpm
    ports:
      - "6670:6670"
      - "8888:8888"
      - "6669:6669"
    environment:
    - VIRTUAL_HOST=prespot.shalltry.com,csh3.ngrok.hanwide.com
    - WEB_DOCUMENT_ROOT=/app/web
    volumes:
    - /data/node_web/h5/:/app/web
    - /data/node_web/h5/tecno-spot-h5/nginx-node.conf:/etc/nginx/conf.d/default.conf
    network_mode: docker_network